// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CS_test_2 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void CS_test_2() {
    // Test name: 2
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.manchester.ac.uk/");
    // 2 | setWindowSize | 1554x840 | 
    driver.manage().window().setSize(new Dimension(1554, 840));
    // 3 | mouseOver | id=megaLink-study | 
    {
      WebElement element = driver.findElement(By.id("megaLink-study"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | css=.search-icon > span | 
    driver.findElement(By.cssSelector(".search-icon > span")).click();
    // 5 | click | id=searchBox | 
    driver.findElement(By.id("searchBox")).click();
    // 6 | type | id=searchBox | computer science
    driver.findElement(By.id("searchBox")).sendKeys("computer science");
    // 7 | click | css=.searchInputWrapper2 > input | 
    driver.findElement(By.cssSelector(".searchInputWrapper2 > input")).click();
    // 8 | click | linkText=Department of Computer Science - The University of Manchester | 
    driver.findElement(By.linkText("Department of Computer Science - The University of Manchester")).click();
    // 9 | click | linkText=Undergraduate courses (2026 entry) | 
    driver.findElement(By.linkText("Undergraduate courses (2026 entry)")).click();
    // 10 | click | id=customSearch | 
    driver.findElement(By.id("customSearch")).click();
    // 11 | type | id=customSearch | computer science
    driver.findElement(By.id("customSearch")).sendKeys("computer science");
    // 12 | click | css=#id00560 a | 
    driver.findElement(By.cssSelector("#id00560 a")).click();
    // 13 | close |  | 
    driver.close();
  }
}
