// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CS_test_3 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void CS_test_3() {
    // Test name: 3
    // Step # | name | target | value
    // 1 | open | /study/student-terms-and-conditions/ | 
    driver.get("https://www.manchester.ac.uk/study/student-terms-and-conditions/");
    // 2 | setWindowSize | 1554x840 | 
    driver.manage().window().setSize(new Dimension(1554, 840));
    // 3 | click | linkText=Undergraduate | 
    driver.findElement(By.linkText("Undergraduate")).click();
    // 4 | click | linkText=Courses | 
    driver.findElement(By.linkText("Courses")).click();
    // 5 | click | css=.more | 
    driver.findElement(By.cssSelector(".more")).click();
    // 6 | type | id=custom-search | computer science
    driver.findElement(By.id("custom-search")).sendKeys("computer science");
    // 7 | click | css=#course-search-buttons > input:nth-child(1) | 
    driver.findElement(By.cssSelector("#course-search-buttons > input:nth-child(1)")).click();
    // 8 | click | css=#id00560 a | 
    driver.findElement(By.cssSelector("#id00560 a")).click();
    // 9 | close |  | 
    driver.close();
  }
}
