// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.time.Duration;
import java.util.*;

public class ComputerScienceFirstTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new EdgeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void ComputerScience() {
    // Test name: 用户故事1：-正常路径-目的地Computer Science
    // Step # | name | target | value | comment
    // 1 | open | / |  |
    driver.get("https://www.manchester.ac.uk/");
    // 2 | setWindowSize | 1119x911 |  |
    driver.manage().window().setSize(new Dimension(1119, 911));
    // 3 | waitForElementPresent | id=megaLink-study | 10000 |
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("megaLink-study")));
    }
    // 4 | mouseOver | id=megaLink-study |  |
    {
      WebElement element = driver.findElement(By.id("megaLink-study"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 5 | assertText | id=megaLink-study | Study |
    assertThat(driver.findElement(By.id("megaLink-study")).getText(), is("Study"));
    // 7 | click | id=megaLink-study |  |
    driver.findElement(By.id("megaLink-study")).click();
    // 9 | click | linkText=Undergraduate |  |
    driver.findElement(By.linkText("Undergraduate")).click();
    // 11 | click | linkText=View all courses |  |
    driver.findElement(By.linkText("View all courses")).click();
    // 12 | runScript | window.scrollTo(0,75) |  |
    js.executeScript("window.scrollTo(0,75)");
    // 14 | click | css=.breadcrumbItem:nth-child(1) > a |  |
    driver.findElement(By.cssSelector(".breadcrumbItem:nth-child(1) > a")).click();
    // 16 | click | css=.search-icon > span |  |
    driver.findElement(By.cssSelector(".search-icon > span")).click();
    // 17 | type | id=searchBox | Computer Science |
    driver.findElement(By.id("searchBox")).sendKeys("Computer Science");
    // 18 | click | css=.searchInputWrapper2 > input |  |
    driver.findElement(By.cssSelector(".searchInputWrapper2 > input")).click();
    // 20 | assertText | css=h1 | Search |
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Search"));
    // 21 | mouseOver | id=megaLink-study |  |
    {
      WebElement element = driver.findElement(By.id("megaLink-study"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 22 | click | linkText=Undergraduate |  |
    driver.findElement(By.linkText("Undergraduate")).click();
    // 24 | click | css=.label |  |
    driver.findElement(By.cssSelector(".label")).click();
    // 25 | type | id=courseKeywords | Computer Science |
    driver.findElement(By.id("courseKeywords")).sendKeys("Computer Science");
    // 26 | click | name=submit |  |
    driver.findElement(By.name("submit")).click();
    // 27 | runScript | window.scrollTo(0,184) |  |
    js.executeScript("window.scrollTo(0,184)");
    // 29 | click | css=#id00560 a |  |
    driver.findElement(By.cssSelector("#id00560 a")).click();
    // 30 | runScript | window.scrollTo(0,0) |  |
    js.executeScript("window.scrollTo(0,0)");
    // 32 | click | css=h1 |  |
    driver.findElement(By.cssSelector("h1")).click();
    // 33 | assertText | css=h1 | BSc Computer Science |
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("BSc Computer Science"));
    // 34 | close | / |  |
    driver.close();
  }
}