// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import java.util.concurrent.TimeUnit;
import java.time.Duration;
import java.util.*;

public class ComputerScienceSecondTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new EdgeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void ComputerScience() {
    // Test name: 用户故事2：-其他路径-目的地Computer Science
    // Step # | name | target | value | comment
    // 1 | open | / |  |
    driver.get("https://www.manchester.ac.uk/");
    // 2 | setWindowSize | 1119x911 |  |
    driver.manage().window().setSize(new Dimension(1119, 911));
    // 3 | waitForElementPresent | id=megaLink-study | 10000 |
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("megaLink-study")));
    }
    // 4 | click | css=.search-icon > span |  |
    driver.findElement(By.cssSelector(".search-icon > span")).click();
    // 6 | type | id=searchBox | Computer Science |
    driver.findElement(By.id("searchBox")).sendKeys("Computer Science");
    // 7 | click | css=.searchInputWrapper2 > input |  |
    driver.findElement(By.cssSelector(".searchInputWrapper2 > input")).click();
    // 8 | click | linkText=Women and gender-diversity in computer science - Department of Computer Science - The University of Manchester |  |
    driver.findElement(By.linkText("Women and gender-diversity in computer science - Department of Computer Science - The University of Manchester")).click();
    // 9 | runScript | window.scrollTo(0,0) |  |
    js.executeScript("window.scrollTo(0,0)");
    // 11 | mouseOver | linkText=Study |  |
    {
      WebElement element = driver.findElement(By.linkText("Study"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }

    // 12 | click | linkText=Undergraduate |  |
    driver.findElement(By.linkText("Undergraduate")).click();
    // 添加等待：等待侧边栏菜单加载完成
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(20));
      wait.until(ExpectedConditions.presenceOfElementLocated(
              By.xpath("//aside[@class='leftMenuContainer showAtDesktop']")));
    }

    // 13 | assertText | css=h1 | Undergraduate |
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Women and gender-diversity in computer science"));

    // 14 | click | linkText=Courses |  |
    driver.findElement(By.xpath("//aside[@class='leftMenuContainer showAtDesktop']//a[contains(@href, '/study/undergraduate/courses/')]")).click();
    // 16 | click | css=.mainLogo img |  |
    driver.findElement(By.cssSelector(".mainLogo img")).click();
    // 17 | mouseOver | id=megaLink-study |  |
    {
      WebElement element = driver.findElement(By.id("megaLink-study"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 18 | click | css=#panel-study-undergraduate li:nth-child(1) > a |  |
    driver.findElement(By.cssSelector("#panel-study-undergraduate li:nth-child(1) > a")).click();
    // 19 | runScript | window.scrollTo(0,756) |  |
    js.executeScript("window.scrollTo(0,756)");
    // 20 | click | css=.more |  |
    driver.findElement(By.cssSelector(".more")).click();
    // 21 | runScript | window.scrollTo(0,126) |  |
    js.executeScript("window.scrollTo(0,126)");
    // 23 | click | id=custom-search |  |
    driver.findElement(By.id("custom-search")).click();
    // 24 | type | id=custom-search | Computer Science |
    driver.findElement(By.id("custom-search")).sendKeys("Computer Science");
    // 25 | click | css=#course-search-buttons > input:nth-child(1) |  |
    driver.findElement(By.cssSelector("#course-search-buttons > input:nth-child(1)")).click();
    // 26 | runScript | window.scrollTo(0,424) |  |
    js.executeScript("window.scrollTo(0,424)");
    // 27 | click | css=#id00560 a |  |
    driver.findElement(By.cssSelector("#id00560 a")).click();
    // 28 | mouseOver | linkText=2026 entry |  |
    {
      WebElement element = driver.findElement(By.linkText("2026 entry"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 29 | mouseOut | linkText=2026 entry |  |
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 30 | runScript | window.scrollTo(0,0) |  |
    js.executeScript("window.scrollTo(0,0)");
    // 31 | click | css=h1 |  |
    driver.findElement(By.cssSelector("h1")).click();
    // 32 | assertText | css=h1 | BSc Computer Science |
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("BSc Computer Science"));
    // 33 | close |  |  |
    driver.close();
  }
}
