// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.time.Duration;
import java.util.*;

public class ComputerScienceThirdTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new EdgeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void ComputerScience() {
    // Test name: 用户故事3：-异常路径-目的地Computer Science
    // Step # | name | target | value | comment
    // 1 | open | / |  |
    driver.get("https://www.manchester.ac.uk/");
    // 2 | setWindowSize | 1119x911 |  |
    driver.manage().window().setSize(new Dimension(1119, 911));
    // 3 | mouseOver | id=megaLink-study |  |
    {
      WebElement element = driver.findElement(By.id("megaLink-study"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 5 | click | css=#panel-study-masters li:nth-child(1) > a |  |
    driver.findElement(By.cssSelector("#panel-study-masters li:nth-child(1) > a")).click();
    // 6 | click | css=.primaryLeftNavNew .breadcrumbItem:nth-child(3) > a |  |
    driver.findElement(By.cssSelector(".primaryLeftNavNew .breadcrumbItem:nth-child(3) > a")).click();
    // 8 | click | css=.label |  |
    driver.findElement(By.cssSelector(".label")).click();
    // 9 | mouseOver | name=submit |  |
    {
      WebElement element = driver.findElement(By.name("submit"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 10 | type | id=courseKeywords | Computer Science |
    driver.findElement(By.id("courseKeywords")).sendKeys("Computer Science");
    // 11 | click | name=submit |  |
    driver.findElement(By.name("submit")).click();
    // 13 | click | css=#id21573 a |  |
    driver.findElement(By.cssSelector("#id21573 a")).click();
    // 14 | click | css=h1 |  |
    driver.findElement(By.cssSelector("h1")).click();
    // 15 | assertNotText | css=h1 | Computer Science |
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is(not("Computer Science")));
    // 17 | mouseOver | id=megaLink-study |  |
    {
      WebElement element = driver.findElement(By.id("megaLink-study"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 18 | click | css=#panel-study-undergraduate li:nth-child(1) > a |  |
    driver.findElement(By.cssSelector("#panel-study-undergraduate li:nth-child(1) > a")).click();
    // 19 | click | css=.primaryLeftNavNew .breadcrumbItem:nth-child(2) > a |  |
    driver.findElement(By.cssSelector(".primaryLeftNavNew .breadcrumbItem:nth-child(2) > a")).click();
    // 20 | click | linkText=Undergraduate |  |
    driver.findElement(By.linkText("Undergraduate")).click();
    // 22 | click | linkText=Courses |  |
    driver.findElement(By.linkText("Courses")).click();
    // 23 | runScript | window.scrollTo(0,525) |  |
    js.executeScript("window.scrollTo(0,525)");
    // 24 | waitForElementPresent | id=megaLink-study | 10000 |
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("megaLink-study")));
    }
    // 25 | click | css=.more |  |
    driver.findElement(By.cssSelector(".more")).click();
    // 26 | mouseOver | id=advanced-toggle |  |
    {
      WebElement element = driver.findElement(By.id("advanced-toggle"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 27 | click | id=custom-search |  |
    driver.findElement(By.id("custom-search")).click();
    // 28 | type | id=custom-search | Computer Science |
    driver.findElement(By.id("custom-search")).sendKeys("Computer Science");
    // 29 | click | css=#course-search-buttons > input:nth-child(1) |  |
    driver.findElement(By.cssSelector("#course-search-buttons > input:nth-child(1)")).click();
    // 30 | click | css=#id00560 a |  |
    driver.findElement(By.cssSelector("#id00560 a")).click();
    // 31 | runScript | window.scrollTo(0,0) |  |
    js.executeScript("window.scrollTo(0,0)");
    // 33 | click | css=h1 |  |
    driver.findElement(By.cssSelector("h1")).click();
    // 34 | assertText | css=h1 | BSc Computer Science |
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("BSc Computer Science"));
    // 35 | close |  |  |
    driver.close();
  }
}